be_teen_admin_index:
    path:       /
    defaults:   { _controller: BeTeenAdminBundle:Admin:Index }

be_teen_admin_forum:
    path:       /forum
    defaults:   { _controller: BeTeenAdminBundle:Forum:Index }
    
be_teen_admin_forum_initialize:
    path:       /forum/initialize
    defaults:   { _controller: BeTeenAdminBundle:Forum:Initialize }
    
be_teen_admin_forum_categories:
    path:       /forum/categories/{categorie}
    defaults:   { _controller: BeTeenAdminBundle:Forum:Categories ,categorie: index}
    
be_teen_admin_forum_categories_monter:
    path:       /forum/categories/{categorie}/monter
    defaults:   { _controller: BeTeenAdminBundle:Forum:MonterCategorie}
    
be_teen_admin_forum_categories_descendre:
    path:       /forum/categories/{categorie}/descendre
    defaults:   { _controller: BeTeenAdminBundle:Forum:DescendreCategorie}
    
be_teen_admin_forum_categories_supprimer:
    path:       /forum/categories/{categorie}/supprimer
    defaults:   { _controller: BeTeenAdminBundle:Forum:SupprimerCategorie}
    
be_teen_admin_forum_categories_ajouter:
    path:       /forum/categories/{parent}/ajouter
    defaults:   { _controller: BeTeenAdminBundle:Forum:AjouterCategorie}
    
be_teen_admin_forum_categories_modifier:
    path:       /forum/categories/{categorie}/modifier
    defaults:   { _controller: BeTeenAdminBundle:Forum:ModifierCategorie}
    
be_teen_admin_forum_categories_sujetswitch:
    path:       /forum/categories/{categorie}/sujet-switch
    defaults:   { _controller: BeTeenAdminBundle:Forum:SwitchAllowSujet}
    
be_teen_admin_forum_sujets:
    path:       /forum/sujets
    defaults:   { _controller: BeTeenAdminBundle:Forum:Sujets }
    
be_teen_admin_forum_sujets_supprimer:
    path:       /forum/sujets/supprimer-{sujet}
    defaults:   { _controller: BeTeenAdminBundle:Forum:SupprimerSujet }
    
be_teen_admin_forum_sujets_verouillageswitch:
    path:       /forum/sujets/verouillage-{sujet}
    defaults:   { _controller: BeTeenAdminBundle:Forum:VerouillageSujet }
    
be_teen_admin_user:
    path:       /utilisateur
    defaults:   { _controller: BeTeenAdminBundle:User:Index }
    
be_teen_admin_user_liste:
    path:       /utilisateur/liste
    defaults:   { _controller: BeTeenAdminBundle:User:List }
    
be_teen_admin_user_ajout:
    path:       /utilisateur/ajouter
    defaults:   { _controller: BeTeenAdminBundle:User:Ajout }
    
be_teen_admin_user_modifier:
    path:       /utilisateur/modifier/{user}
    defaults:   { _controller: BeTeenAdminBundle:User:Modifier }