be_teen_admin_index:
    path:       /
    defaults:   { _controller: BeTeenAdminBundle:Admin:Index }

be_teen_admin_forum:
    path:       /forum
    defaults:   { _controller: BeTeenAdminBundle:Forum:Index }
    
#be_teen_admin_forum_categories:
#    path:       /forum/categories
#    delaults:   { _controller: BeTeenAdminBundle:Forum:Categories }
    
be_teen_admin_forum_sujets:
    path:       /forum/sujets
    defaults:   { _controller: BeTeenAdminBundle:Forum:Sujets }